// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210627021521_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Domain.Channel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            id = new Guid("eb60446d-45f9-4815-b245-632e1e24a074"),
                            description = "Canal de .NET CORE",
                            name = ".NET CORE"
                        },
                        new
                        {
                            id = new Guid("9b243419-e787-41e7-8b49-6d2cdf52c87d"),
                            description = "Canal de ReactJs",
                            name = "ReactJs"
                        },
                        new
                        {
                            id = new Guid("08050080-875f-4dfd-9093-e28132b197d3"),
                            description = "Canal de Angular",
                            name = "Angular"
                        },
                        new
                        {
                            id = new Guid("fbb486bb-0fe9-4e6b-b5f5-c93ac9acf21d"),
                            description = "Canal de Vue",
                            name = "Vue"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
